---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: unless-stopped

volumes:
  uptime-kuma-data:
