---
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud #optional
      - MYSQL_USER=nextcloud #optional
      - MYSQL_PASSWORD=nextcloud #optional
    volumes:
      - nextcloud_db_config:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - nextcloud_config:/config
      - /mnt/nextcloud/userdata:/data
    ports:
      - 442:443
    restart: unless-stopped
    depends_on:
      - mariadb

volumes:
  nextcloud_db_config:
  nextcloud_config:
