version: '3'
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /srv/homarr/configs:/app/data/configs
      - /srv/homarr/icons:/app/public/icons
      - /srv/homarr/data:/data
    ports:
      - '7575:7575'
